<?php

namespace AppBundle\Entity;

use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * FortuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeratedRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLast()
  {
    $queryBuilder = $this->createQueryBuilder('f')
      ->orderBy("f.id", "DESC");

    return new DoctrineORMAdapter($queryBuilder);
  }

}
